//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChemFormatter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChemFormatter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chem Formula.
        /// </summary>
        public static string TextChemFormula {
            get {
                return ResourceManager.GetString("TextChemFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chem Name.
        /// </summary>
        public static string TextChemName {
            get {
                return ResourceManager.GetString("TextChemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation.
        /// </summary>
        public static string TextCitation {
            get {
                return ResourceManager.GetString("TextCitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Formula.
        /// </summary>
        public static string TextIonFormula {
            get {
                return ResourceManager.GetString("TextIonFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMR Format.
        /// </summary>
        public static string TextNMRFormat {
            get {
                return ResourceManager.GetString("TextNMRFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NMR Spec.
        /// </summary>
        public static string TextNMRSpec {
            get {
                return ResourceManager.GetString("TextNMRSpec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Rotation.
        /// </summary>
        public static string TextOpticalRotation {
            get {
                return ResourceManager.GetString("TextOpticalRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style as char.
        /// </summary>
        public static string TextStyleAsChar {
            get {
                return ResourceManager.GetString("TextStyleAsChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub. Digit Change.
        /// </summary>
        public static string TextSubDigitsChange {
            get {
                return ResourceManager.GetString("TextSubDigitsChange", resourceCulture);
            }
        }
    }
}
